// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OgretmenAtama.Persistance.Data.Contexts;

#nullable disable

namespace OgretmenAtama.Persistance.Migrations
{
    [DbContext(typeof(OgretmenAtamaDbContext))]
    [Migration("20220731193856_mig_3")]
    partial class mig_3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OgretmenAtama.Domain.Entities.Concrete.Alanlar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlanAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AlanKodu")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Alanlar");
                });

            modelBuilder.Entity("OgretmenAtama.Domain.Entities.Concrete.Ilceler", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("IlKodu")
                        .HasColumnType("smallint");

                    b.Property<string>("IlceAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Ilceler");
                });

            modelBuilder.Entity("OgretmenAtama.Domain.Entities.Concrete.Iller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IlAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("IlHizmetBolgesi")
                        .HasColumnType("smallint");

                    b.Property<byte>("IlKodu")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Iller");
                });

            modelBuilder.Entity("OgretmenAtama.Domain.Entities.Concrete.Kurumlar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KurumAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("KurumHizmetAlani")
                        .HasColumnType("smallint");

                    b.Property<int>("KurumKodu")
                        .HasColumnType("integer");

                    b.Property<byte>("KurumTipi")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Kurumlar");
                });

            modelBuilder.Entity("OgretmenAtama.Domain.Entities.Concrete.KurumlarAlanlar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AlanKodu")
                        .HasColumnType("integer");

                    b.Property<int>("BosKontenjan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("KurumKodu")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("KurumlarAlanlar");
                });
#pragma warning restore 612, 618
        }
    }
}
